project_id = "illckjvvbcqavladafsc"
[functions.check-dividend-notifications]
verify_jwt = false


[functions.stock-quotes]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.monthly-report]
verify_jwt = false

[functions.cakto-webhook]
verify_jwt = false

[functions.fetch-dividends]
verify_jwt = false

[functions.admin-upgrade-subscription]
verify_jwt = false

[functions.admin-set-role]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.exchange-rate]
verify_jwt = false
