project_id = "illckjvvbcqavladafsc"

[functions.stock-quotes]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[auth]
site_url = "https://myinvestapp.lovable.app"

[auth.email]
enable_confirmations = true

[auth.email.template.recovery]
subject = "Redefinir Senha - My Invest ğŸ”"
content_path = "./templates/recovery.html"

[auth.email.template.confirmation]
subject = "Confirme seu Email - My Invest âœ‰ï¸"
content_path = "./templates/confirmation.html"

[auth.email.template.invite]
subject = "VocÃª foi convidado - My Invest ğŸ’°"
content_path = "./templates/invite.html"

[auth.email.template.magic_link]
subject = "Seu link de acesso - My Invest ğŸ”‘"
content_path = "./templates/magic_link.html"

[auth.email.template.email_change]
subject = "Confirme a alteraÃ§Ã£o de email - My Invest âœ‰ï¸"
content_path = "./templates/email_change.html"
